dbt_tpch:
  outputs:
    dev:
      type: duckdb
      extensions:
        - ducklake
        - postgres
      path: /tmp/dev.duckdb
      threads: 2
      secrets:
        - type: s3
          provider: config
          key_id: "{{ env_var('DUCKDB_S3_ACCESS_KEY_ID') }}"
          secret: "{{ env_var('DUCKDB_S3_SECRET_ACCESS_KEY') }}"
          region: "{{ env_var('DUCKDB_S3_REGION') }}"
      attach:
        - path: "ducklake:~/project/ducklake-sandbox/metadata.ducklake"
          alias: ducklake
          is_ducklake: true
          options:
            data_path: s3://dlsandbox/tpch/
      database: ducklake
  target: dev



      #   s3_endpoint: "{{ env_var('DUCKDB_S3_ENDPOINT') }}"
      #   s3_access_key_id: "{{ env_var('DUCKDB_S3_ACCESS_KEY_ID') }}"
      #   s3_secret_access_key: "{{ env_var('DUCKDB_S3_SECRET_ACCESS_KEY') }}"
      #   s3_region: "{{ env_var('DUCKDB_S3_REGION') }}"
      #   s3_url_style: "{{ env_var('DUCKDB_S3_URL_STYLE') }}"
      #   s3_use_ssl: {{ env_var('DUCKDB_S3_USE_SSL') | as_bool }}
