dbt_tpch:
  outputs:
    dev:
      type: duckdb
      extensions:
        - ducklake
        - postgres
      path: /tmp/dev.duckdb
      threads: 2
      schema: main # <-- схема по умолчанию для разработки
      secrets:
        - type: s3
          provider: config
          key_id: "{{ env_var('DUCKDB_S3_ACCESS_KEY_ID') }}"
          secret: "{{ env_var('DUCKDB_S3_SECRET_ACCESS_KEY') }}"
          region: "{{ env_var('DUCKDB_S3_REGION') }}"
          endpoint: "{{ env_var('DUCKDB_S3_ENDPOINT') }}"    # или "127.0.0.1:9000"
          url_style: "{{ env_var('DUCKDB_S3_URL_STYLE') }}"  #"path" 
          use_ssl: "{{ env_var('DUCKDB_S3_USE_SSL') }}"      # false
      attach:
        - path: "ducklake:~/project/ducklake-sandbox/metadata.ducklake"
          alias: ducklake
          is_ducklake: true
      database: ducklake
  target: dev

